# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 20


[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 30

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 40

[[main]]
  name = "Services"
  url = "#professional_services"
  weight = 50

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 60

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 70

[[main]]
  name = "Recent Posts"
  url = "#posts"
  weight = 80

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 90
  
[[main]]
  name = "Blog"
  url = "http://blog.jinlaixu.net"
  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
